# Generated by Django 3.2.5 on 2021-07-27 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('parent', models.CharField(choices=[('Course', 'Course'), ('Tutorial', 'Tutorial'), ('Workshop', 'Workshop'), ('Company', 'Company')], max_length=200, null=True)),
                ('Description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20, null=True)),
                ('level', models.CharField(choices=[('Intermediate', 'Intermediate'), ('Beginners', 'Beginners'), ('Advance', 'Advance')], max_length=200)),
                ('Description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image_cover', models.FileField(upload_to='images')),
                ('video', models.FileField(upload_to='video')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.category')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('contenu', models.FileField(blank=True, null=True, upload_to='course/section/lecture')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.section')),
            ],
        ),
    ]
