# Generated by Django 3.2.5 on 2021-07-29 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='contenu',
        ),
    ]
