# Generated by Django 3.2.5 on 2021-08-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_lecture_contenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
