# Generated by Django 3.2.5 on 2021-08-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lecture_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to='video'),
        ),
    ]
