# Generated by Django 3.2.5 on 2021-08-05 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_pdf_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='section',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
