# Generated by Django 3.2.5 on 2021-08-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20210805_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='content',
        ),
        migrations.AddField(
            model_name='lecture',
            name='extention',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
